### PR TITLE
added BamFileResource class

### PR DESCRIPTION
**Pull request by FelixErnst**
to load a BamFile from ExperimentHub/AnnotationHub data. Ro be used like the FaFileResource class

If this exists somewhere else, please disregard it.

### CODE REVIEW

**Comment by lshep** [comment]
This is a good start but I believe I have to figure out how the resources are added in such a way that two resources are associated with a single ah_id and provide some documentation on how to specify this in the metadata ... I'll try to investigate this more asap.

**Comment by FelixErnst** [comment]
The reference I used was for the FaFileResource, since both BamFile and FaFile derive from the same class inside the Rsamtools package

```
ah <- AnnotationHub()
mcols(subset(ah, ah$rdataclass == "FaFile" & ah$species=='Drosophila melanogaster'))
```

From the example above I deduced, that the rdatapath must include the .fasta and .fai file separated by a comma. This is also a scenario usable for bam and bai files.

I ran into a little problem during creation of the metadata. RDataPath can not include a blank space. Therefore I don't know, why rdatapath in the example above shows a blank space after the comma.

**Comment by FelixErnst** [comment]
Hi @lshep 

would it be possible to push the data I uploaded to the AnnotationHub/ExperimentHub backend (the "RNAmodR.Data" package)? Maybe I can test stuff on my end as well and finish this.

Best regards

**Comment by lshep** [comment]
I'm sorry for the delay and I will get to this as soon as possible. We are a little swamped with it being the release this coming week.  I want to look this over in detail so I can make sure the resources get added correctly to the database - This is a simplified view for the end user, which is why there are spaces and commas that wouldn't be present in the metadata.csv file - I need to make sure that the database adds the resources correctly and how that is accomplished and the correct syntax for the metadata.csv file.

**Comment by FelixErnst** [comment]
Of course, as I mentioned I can help debug this regarding the actual use of the Resource classes.

When you have Infos on the necessity of the fai files (which by accident I didn't include in the upload), please let me know. This relates to the question from the mail:
> One additional question came up yesterday: Within the .get1 function for FaFileResource: Does the fa[2] value contain NA or NULL if only the fasta file is referenced in metadata? (If it is NULL, I Need to upload the fai file as well. Are the credential still active and can I just reupload the whole Directory?)

**Comment by lshep** [comment]
I think I will need to adjust the makeAnnotationHubMetadata  for this to work properly.  When I add resources to the data base I create the list of values using this function and then push it to the database.  
```
```

**Comment by lshep** [comment]
I think I (we/someone) will need to adjust the AnnotationHubData:::.readMetadataFromCsv for this to work properly. When I add resources to the data base I create the list of values using makeAnnotationHubMetadata or makeExpermentHubMetadata which in turn calls this internal function that parses the metadata.csv  

For example with a package data I added earlier today:
```
> meta = makeExperimentHubMetadata("muscData/")
missing or NA values for 'Coordinate_1_based set to TRUE'
Loading valid species information.
> meta
[[1]]
ExperimentHubMetadata object: 
Title: Kang18_8vs8
Description: Droplet-based scRNA-seq PBMC data from 8 Lupus patients
  before and after 6h-treatment with INF-beta. Represented as a
  SingleCellExperiment; derived from GEO accession number GSE96583.
BiocVersion: 3.9
Genome: NA
Species: Homo sapiens
TaxonomyId: 9606
Location_Prefix: http://s3.amazonaws.com/experimenthub/
RDataClass: SingleCellExperiment
RDataDateAdded: 2019-04-23
RDataPath: muscData/Kang18_8vs8.Rda
SourceLastModifiedDate: NA
SourceType: tar.gz
SourceUrl: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96583
SourceVersion: Mar 27 2019
Tags: ExperimentHub ExperimentData ExpressionData SingleCellData
  ImmunoOncologyData Homo_sapiens_Data
DispatchClass: Rda
Package: muscData
```

In the past it looks like we had specialized methods/recipes for FaFiles that would  convert the RDataPath into a character list for these AnnotationHubMetadata objects. https://github.com/Bioconductor/AnnotationHubData/blob/master/R/makeEnsemblFasta.R#L145

```
> meta[[1]]
class: AnnotationHubMetadata
AnnotationHubRoot: NA
BiocVersion: 3.9
Coordinate_1_based: TRUE
DataProvider: Ensembl
DerivedMd5: NA
Description: FASTA cDNA sequence for Acanthochromis polyacanthus
DispatchClass: FaFile
Error: NA_character
Genome: ASM210954v1
HubRoot: NA
Location_Prefix: http://s3.amazonaws.com/annotationhub/
Maintainer: Bioconductor Maintainer <maintainer@bioconductor.org>
Notes: NA
PreparerClass: NA
RDataClass: FaFile FaFile FaFile
RDataDateAdded: 2019-04-23
RDataPath:
  ensembl/release-95/fasta/acanthochromis_polyacanthus/cdna/Acanthochromis_polyacanthus.ASM210954v1.cdna.all.fa.bgz
  ensembl/release-95/fasta/acanthochromis_polyacanthus/cdna/Acanthochromis_polyacanthus.ASM210954v1.cdna.all.fa.bgz.gzi
  ensembl/release-95/fasta/acanthochromis_polyacanthus/cdna/Acanthochromis_polyacanthus.ASM210954v1.cdna.all.fa.bgz
Recipe: AnnotationHubData:::ensemblFastaToFaFile
SourceLastModifiedDate: NA
SourceMd5: NA
SourceSize: NA
SourceType: FASTA
SourceUrl:
  ftp://ftp.ensembl.org/pub/release-95/fasta/acanthochromis_polyacanthus/cdna/Acanthochromis_polyacanthus.ASM210954v1.cdna.all.fa.gz
SourceVersion: release-95
Species: Acanthochromis polyacanthus
Tags: FASTA ensembl sequence
TaxonomyId: 80966
Title: Acanthochromis_polyacanthus.ASM210954v1.cdna.all.fa

```  
Right now when we parse the file with we assume that the RDataPath is a single value so perhaps if there is a specific file separator we convert this to the needed character list in `.readMetadataFromCsv`.

**Comment by FelixErnst** [comment]
In https://github.com/Bioconductor/AnnotationHubData/blob/master/R/makeEnsemblFasta.R#L150 It looks like that every second (or third?) entry of a `FaFile` value was/is expected to reference a .fai file.

Since there is no universally disallowed character in Linux, Windows and MacOS, it makes it quite hard to create a system for a single value `RDataPath` referencing multiple files delimited by a single character.

So I think we have two options:
1. Either select a special character to delimit to entries in `RDataPath` for which I would suggest `:`. This is disallowed at least on windows. On Linux there is probably only `/` or `null`, which are both not an option, I think. The check in `.readMetadataFromCsv` would then allow only one instance of the character and both sides of the split `RDataPath` entry have to be equal (minus the file ending)
2. Enforce two entries per FaFile/BamFile/whatever. This would allow very quick checking because `n(entries) mod x`  must be 0. Two following entries would also have to be equal (minus the file ending).

Both are viable options and in my opinion neither has a clear advantage. Which option would you prefer?

I would go for option 1, since it is easier to setup and has not a copy&paste feeling. However, I would maybe get a vote from Martin Morgan or some else, who has more experience and can judge better, if selecting the `:` as the delimiter can cause problems on Linux in some real life scenario.

**Comment by lshep** [comment]
I can probably look into this more tomorrow.

**Comment by lshep** [comment]
I  can look at this more tomorrow. I would vote for 1  and perhaps separate by a space instead of a specific character but I will ask around the group tomorrow.

**Comment by FelixErnst** [comment]
I think this would go than at this location, would it?

https://github.com/Bioconductor/AnnotationHubData/R/AnnotationHubMetadata-class.R#L115

**Comment by lshep** [comment]
yes somewhere around there -  I might have to rework the check below as well 
https://github.com/Bioconductor/AnnotationHubData/blob/master/R/AnnotationHubMetadata-class.R#L145

**Comment by FelixErnst** [comment]
space is quite a tricky character, since I am not sure, if older files might contain a space as a character (There is currently no check for). Additionally, a lot of people use it regularly, when naming files.

So I would suggest something, which is also human readable as a delimiter. For me an alternative to `:` would be something like `<:>`.

**Comment by FelixErnst** [comment]
btw: Can I upload the missing .fai files with the credentials?

**Comment by lshep** [comment]
Yes please upload the missing fai files with the same credentials

**Comment by lshep** [comment]
It can't be a colon as that is used in almost every full web link `https://`  - I'll ask around the office this morning.

**Comment by FelixErnst** [comment]
but according to `?makeExperimentHubMetadata` this is only the remainder of a path, isn't it?
 
The `https://` should be in `Location_Prefix`. So a colon is not a problem is it?

**Comment by FelixErnst** [comment]
I reuploaded to whole data set. The fai files are now included

**Comment by lshep** [comment]
True -  just realized that myself -  but it is also true that we have made a validity check that doesn't allow spaces in the RDataPath file name too -   But after discussion in the group we are thinking `:`  would probably be best -  I'll work on some updates today -

**Comment by FelixErnst** [comment]
Thanks!

**Comment by lshep** [comment]
Getting close I think -  I hope to have an update soon.

**Comment by lshep** [comment]
I think I have an update for everything ready - I'm reviewing with Martin tomorrow and hopefully will be able to push tomorrow afternoon.

**Comment by lshep** [comment]
So - I'm closing this pull request but it is implemented.  I need to make some slight alterations.  Please separate the RDataPaths with a colon  ":"  for bam and bai files.

**Comment by FelixErnst** [comment]
So the convention is: data file first, index file second? Just want to make sure.

**Comment by lshep** [comment]
Yes separated by a colon

**Comment by FelixErnst** [comment]
Thanks for working on this issue during these busy time of the year. Much appreciated!

**Comment by lshep** [comment]
It was long overdue!

**Pull request closed without merging**
