### PR TITLE
.Defunct display,Hub-method

### PR DESCRIPTION
**Pull request by LiNk-NY**
Hi Lori, @lshep 

I'm marking display as defunct and removing the `interactiveDisplayBase` dependency. 
I will also prepare `BiocHubsShiny` (the alternative) for submission. 

Best,
Marcel

### CODE REVIEW

**Comment by lshep** [comment]
excellent.  If its okay with you I'd like to wait until the alternate is submitted in the new package queue before merging.

**Comment by lshep** [comment]
When I checkout this branch locally and try to R CMD build / R CMD check I get the following: 

```
lorikern@jbcj433:~/BioconductorPackages/SoftwarePkg$ R CMD build AnnotationHub
* checking for file 'AnnotationHub/DESCRIPTION' ... OK
* preparing 'AnnotationHub':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
* installing *source* package 'AnnotationHub' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in setMethod("display", signature(object = "Hub"), function(object) { : 
  no existing definition for function 'display'
Error: unable to load R code in package 'AnnotationHub'
Execution halted
ERROR: lazy loading failed for package 'AnnotationHub'
* removing '/tmp/RtmpbUDTQO/Rinstaee816145889/AnnotationHub'
      -----------------------------------
ERROR: package installation failed

```

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
Thanks for pointing it out. I have fixed it. 
It looks like my whitespace settings on RStudio have changed the entire vignette. I will look force updating...
-MR

**Comment by LiNk-NY** [comment]
**Update**: The changes should be better reflected in the diff. 
Thanks!

**Pull request merged**
