### PR TITLE
fixed windows specific BamFile loading error

### PR DESCRIPTION
**Pull request by FelixErnst**

### CODE REVIEW

**Comment by FelixErnst** [comment]
Tested on Windows and Linux using BioC 3.9/R 3.6

**Comment by FelixErnst** [comment]
should fix the problems surfacing here:

https://github.com/Bioconductor/Contributions/issues/1106

**Comment by mtmorgan** [comment]
The plan is instead to allow Rsamtools to read index files without '.bai' extensions, which is done in https://github.com/Bioconductor/Rsamtools/commit/f76b367f979ba4e7e2121034112994b06d7cd577 (will be v. 2.1.1 in devel; when that builds without problem it'll be ported to release). The AnnotationHub recipe should be modified to simply read the index file as downloaded.

**Comment by FelixErnst** [comment]
thanks for the fix. so this will hit the SPB probably tomorrow. Is there a plan for the update of AnnotationHub?

**Comment by lshep** [comment]
There is a major bug in the devel version of the hubs that I'm working on now... once that is fixed and once the Rsamtools propagates I will fix the AnnotatinoHub recipe ...

**Comment by FelixErnst** [comment]
Thanks for the info.

**Pull request closed without merging**
